########################################################################

# avec sudo ansible-playbook -c local config.vm1.yml
---
- hosts: localhost
  tasks:
    # adresse IPv4 avec nmcli (CLI pour NetworkManager)
    # éventuellement, pour supprimer les connexions en trop, faire
    # $ nmcli connection del ansible-eth1
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True
    - shell: nmcli connection del "Connexion filaire 2" 
      ignore_errors: True
    - shell: nmcli connection del "Lan1-6"
      ignore_errors: True
    - shell: nmcli connection del "Lan2-6" 
      ignore_errors: True
    - shell: nmcli connection add ifname eth1 con-name Lan1-6 type ethernet ip6 fc00:1234:1::26/64 gw6 fc00:1234:1::16
    - shell: nmcli connection add ifname eth2 con-name Lan2-6 type ethernet ip6 fc00:1234:2::26/64 gw6 fc00:1234:2::36
    - sysctl: name="net.ipv6.conf.all.forwarding" value=1 sysctl_set=yes state=present reload=yes


      
